### ISSUE TITLE
Usuarios puntúan la participación al reto

### ISSUE THREAD

**Issue by CristinaRodPalm** [CristinaRodPalm/DoIt#1]

**Comment by CristinaRodPalm** [comment]
Falta la parte de front-end @davidsolanes2 @Julianegpo guapus!

**Comment by Julianegpo** [comment]
Se pueden ver todas las participaciones de un reto.
Elusuario logeado puede ver sus propias participaciones y a qué reto están dirigidas:

14ab329ddc47e1eb41ca0d05e7193de9b48ec6c1

No ha sido posible puntuar las participaciones debido a la falta de tiempo.
