### ISSUE TITLE
Apuntarte a un evento

### ISSUE THREAD

**Issue by Julianegpo** [CristinaRodPalm/DoIt#24]

**Comment by CristinaRodPalm** [comment]
Gestionando en issue #25

**Comment by CristinaRodPalm** [comment]
hecho en commit 

> 4e719e8319a88368d988281901ac99c100f29c5f

Falta hacer que el botón de apuntarse no se muestre si ya estás apuntado. 
Eventos a los que estás apuntado en la parte superior!!

**Comment by Julianegpo** [comment]
Haciendo el HTML para ver el resultado final.
