### ISSUE TITLE
Invitar amigo a un evento

### ISSUE THREAD

**Issue by CristinaRodPalm** [CristinaRodPalm/DoIt#4]
Enviar invitación para un evento. Sólo lo pueden hacer quienes estén en el evento.

**Comment by Julianegpo** [comment]
Dos commits:

Visualización de las invitaciones en una página: e1f4f5f0d05cf4a4e0713cb497d2dc2bb176d214

Gestión de las mismas (aceptar/rechazar): 6294a1672c0fdff12506c54744e0d821692cc789

**Comment by Julianegpo** [comment]
Commits relacionados más arriba. Issue cerrada.
