### ISSUE TITLE
Aceptar y rechazar amistad

### ISSUE THREAD

**Issue by CristinaRodPalm** [CristinaRodPalm/DoIt#6]
El update de amistad debe aceptar la petición. Si no está aceptado la hora de resolución es nula.

**Comment by CristinaRodPalm** [comment]
Se han creado dos PutMapping (acceptAmistads, cancelAmistads) que trabajan para aceptar o negar la amistad según el usuario desee.

**Comment by Julianegpo** [comment]
Se necesita saber la estructura de comunicacion entre back-end y front-end, mediante el app-state y los controllers.

Una vez se sepa eso, no habrán problemas.

**Comment by CristinaRodPalm** [comment]
Back-end finalizado.

**Comment by Julianegpo** [comment]
Ya hemos conseguido averiguar (a medias) cómo funciona la creación de vistas e inyección de las mismas.

En breves procederemos a resolver las issues a nivel de Front-End.

**Comment by CristinaRodPalm** [comment]
Issue terminada en funcionalidad, falta modificar css
